name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install-clean

      - name: Run build
        run: npm run build

      - name: Install test dependencies
        if: matrix.os != 'ubuntu-latest'
        run: npx playwright install chromium --with-deps

      - name: Run unit tests
        run: npm run test:unit
        
      - name: Run E2E tests
        if: matrix.os != 'ubuntu-latest'
        run: npm run test:e2e
